### PR TITLE
Removing no longer used home directory

### PR DESCRIPTION
**Pull request by samhstn**
Don't need the `home` app any more

Ref #225

### CODE REVIEW

**Comment by Danwhy** [comment]
I am actually using this app to hold the landing pages now https://github.com/LDMW/cms/pull/243

**Comment by reddog** [comment]
See #283.  What is the state of this PR?  Is this app required (in which case the PR should be closed)?  Is the fix to make a CMS change (remove the old home page)?

**Comment by reddog** [comment]
As per @shouston3's comment here https://github.com/LDMW/cms/issues/283#issuecomment-328564804,

> using this app to hold the landing pages

refers to the temporary **static** landing pages.

**Comment by reddog** [comment]
@shouston3 @Danwhy Should a suitable label be added to this PR to ensure that it is **not** merged until you want it to be, see https://github.com/LDMW/cms/issues/283#issuecomment-328564804

> we will delete it when the static landing pages are no longer needed

**Comment by samhstn** [comment]
We should tackle more of the issues made in #225, just removing the home directory isn't appropriate at the moment

**Pull request closed without merging**
