### PR TITLE
adding configuration for image upoad

### PR DESCRIPTION
**Pull request by samhstn**
Wagtail changes following [this tutorial](https://wagtail.io/blog/amazon-s3-for-media-files/)

Works in parallel with [LDMW/app#351](https://github.com/LDMW/app/pull/351)

See [LDMW/app#349](https://github.com/LDMW/app/issues/349)

### CODE REVIEW

**Review by Danwhy — APPROVED** [review]

**Comment by nelsonic** [comment]
@shouston3 What is the _rush_? 😕 
image

Referencing the issue/story/requirement in commit message(s), 
completing the PR description and 
requesting review from someone _other_ than the person sitting next to you 
is _not **optional**_...

**Comment by samhstn** [comment]
@nelsonic sorry, we were in a bit of a hurry because while this pr is not in, https://ldmw-app-staging.herokuapp.com may be broken as of these pr's that just got merged [here](https://github.com/LDMW/app/pull/351) (due to our automatic heroku deployments from the github master branch).

This pr should have gone in before this: https://github.com/LDMW/app/pull/351

I'll add a pr description now

**Comment by iteles** [comment]
It really doesn't matter if staging is broken, that's what staging is for. Merging things in without a QA review carries a risk of larger problems. 
Can we please have a retrospective review from @simonlab and see whether we need to open any further issues?

**Comment by samhstn** [comment]
@iteles sorry, I agree, I'll get a retrospective review from @SimonLab

**Review by SimonLab — COMMENTED** [review]
code looks good @shouston3 .

**Pull request merged**
