### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Danwhy**
Initial setup of the new homepage. Requires some back end logic before we can fully implement all of the ui features, such as the search, forms, and filtering by tags.
ref #57, #51

### CODE REVIEW

**Review by samhstn — APPROVED** [review]
Great work @Danwhy 👍

**Comment by Danwhy** [comment]
@nelsonic This is a PR into a branch (`rewrite`) which we have set up to auto deploy to a separate heroku wagtail instance so we can get it ready to transfer over without touching `master`. Would you prefer to review our PRs into that branch as we're working on them, rather than reviewing the whole PR of the rewrite branch into master in one go?

**Comment by nelsonic** [comment]
@Danwhy prefer to review incremental PRs than one big one at the end. 👍

**Review by nelsonic — APPROVED** [review]
@Danwhy looks great!
a few files aren't _strictly_ required e.g: https://github.com/LDMW/cms/blob/da6d89452f77865260a27f9b4a5ffae9d5d2269b/cms/static/images/phoenix.png but overall good to go! 👍

**Pull request merged**
