### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by samhstn**
We can now work from the `master` branch rather than the `rewrite` branch.

I've also changed over the heroku `staging` to have automatic deploys from master.

And the old `ldmw-cms` repo to build from an `old-master` branch

Ref #215

### CODE REVIEW

**Comment by reddog** [comment]
@shouston3 What is this branch for?  Was it a workaround whilst you were trying to get things deployed off to staging?  Can (should?) this branch now be merged with master and normal operations resumed?

**Comment by samhstn** [comment]
The `rewrite` branch was made for when we rewrote the app in python, but also wanted to keep master for the sake of the previous version (further comments here: https://github.com/LDMW/cms/issues/215#issue-252618509)

Yes this branch should get merged in soon.

**Comment by reddog** [comment]
@shouston3 Thanks for that.  re

> Yes this branch should get merged in soon

do we have any idea of when `soon` is?

With regard to #215, the *old* master should be retrievable by inspecting the last commit with the old technical architecture.  Would that suffice?  Maybe a reference somewhere (where?) could be made of that commit ID?  Having a branch *hanging around* just as a reference to the old code might get confusing in time?

**Review by SimonLab — APPROVED** [review]
:+1:

**Pull request merged**
